spring:
  profiles:
    active: login

app:
  users:
    - igorvood
    - arrow-kt
    - inponomarev
#    - ionspin
    - Jeka1978
    - lavcraft
    - xpinjection
    - RSocket
    - Baeldung
    - eugenp
    - yegor256
    - konrad-kaminski
    - aabarmin
    - spring-framework-guru
    - babyfish-ct
#котест и тестирование
    - kochetkov-ma
    - belovaf




save:
#  folder: D:\temp\github_2022_08_30\
  folder: /home/vood/github/